#!/usr/bin/env bash


scbatch_setconfig


SCBATCH_HASH=$(python -c "from notebook.auth import passwd; passwd()")
export SCBATCH_HASH

echo hashed password: $SCBATCH_HASH
echo \# >>   ${SCBATCH_CONFIG}
echo \#*********** >>   ${SCBATCH_CONFIG}
echo 'c.NotebookApp.password = \"$SCBATCH_HASH\"' >> ${SCBATCH_CONFIG}
echo \#*********** >>   ${SCBATCH_CONFIG}
echo \# >>   ${SCBATCH_CONFIG}
