#!/usr/bin/env bash

mkdir - p $(pwd)/.jupyter
JUPYTER_CONFIG_DIR=$(pwd)/.jupyter
export JUPYTER_CONFIG_DIR
export SCBATCH_CONFIG=${JUPYTER_CONFIG_DIR}/jupyter_notebook_config.py

#  -n, --no-clobber  do not overwrite an existing file (overrides a previous -i option)
cp -r --no-clobber /opt/patches/jupyter   ${JUPYTER_CONFIG_DIR}/

python -c "from notebook.auth import passwd; passwd()" > SCBATCH_HASH

export SCBATCH_HASH

echo hashed password: $SCBATCH_HASH
echo \# >>   ${SCBATCH_CONFIG}
echo \#*********** >>   ${SCBATCH_CONFIG}
echo 'c.NotebookApp.password = \"$SCBATCH_HASH\"' >> ${SCBATCH_CONFIG}
echo \#*********** >>   ${SCBATCH_CONFIG}
echo \# >>   ${SCBATCH_CONFIG}
