#!/usr/bin/bash

set -o xtrace
set -o nounset
set -o errexit
#set -o pipefail


scbatch_set_config

# see: http://testnb.readthedocs.io/en/stable/examples/Notebook/Configuring%20the%20Notebook%20and%20Server.html

jupyter notebook \
    --NotebookApp.ip=$(hostname -i)

    # --no-browser

    #--NotebookApp.password=u'sha1:1755c2b99a1c:0b4d6d2c9e14a6218dde77bfbfb15d9062867dc9'
